// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package ots3

import (
	"github.com/go-kit/log"
	"git.yingzhongshare.com/mkt/kitty/pkg/config"
	"git.yingzhongshare.com/mkt/kitty/pkg/contract"
	"net/url"
)

// Injectors from wire.go:

func injectModule(conf contract.ConfigReader, logger log.Logger) *Module {
	manager := provideUploadManager(conf)
	uploadService := &UploadService{
		logger: logger,
		s3:     manager,
	}
	endpoint := MakeUploadEndpoint(uploadService)
	env := config.ProvideEnv(conf)
	securityConfig := provideSecurityConfig(conf)
	middleware := Middleware(logger, env, securityConfig)
	handler := MakeHttpHandler(endpoint, middleware)
	module := &Module{
		handler: handler,
	}
	return module
}

func InjectClientUploader(uri *url.URL) *ClientUploader {
	client := NewClient(uri)
	clientUploader := NewClientUploader(client)
	return clientUploader
}
