// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"git.yingzhongshare.com/mkt/kitty/pkg/contract"
	"git.yingzhongshare.com/mkt/kitty/preload/handlers"
	"github.com/go-kit/log"
)

// Injectors from wire.go:

func injectModule(conf contract.ConfigReader, logger log.Logger) (*Module, func(), error) {
	preloadServer := handlers.NewService(logger)
	module := provideModule(conf, logger, preloadServer)
	return module, func() {
	}, nil
}
