// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: e12fd89529
// Version Date: 2021-03-04T06:59:01Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/lingwei0604/kitty/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC PreloadServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.PreloadServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// preload

		listinfo: grpctransport.NewServer(
			endpoints.ListInfoEndpoint,
			DecodeGRPCListInfoRequest,
			EncodeGRPCListInfoResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the PreloadServer interface
type grpcServer struct {
	listinfo grpctransport.Handler
}

// Methods for grpcServer to implement PreloadServer interface

func (s *grpcServer) ListInfo(ctx context.Context, req *pb.PreloadReq) (*pb.PreloadResp, error) {
	_, rep, err := s.listinfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.PreloadResp), nil
}

// Server Decode

// DecodeGRPCListInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC listinfo request to a user-domain listinfo request. Primarily useful in a server.
func DecodeGRPCListInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.PreloadReq)
	return req, nil
}

// Server Encode

// EncodeGRPCListInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain listinfo response to a gRPC listinfo reply. Primarily useful in a server.
func EncodeGRPCListInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.PreloadResp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
