// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: preload.proto

package kitty

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _preload_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PreloadReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *PreloadReq) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetPreloadHostList() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 2 {
			return PreloadReqValidationError{
				field:  fmt.Sprintf("PreloadHostList[%v]", idx),
				reason: "value length must be at least 2 runes",
			}
		}

		if !strings.HasPrefix(item, "http") {
			return PreloadReqValidationError{
				field:  fmt.Sprintf("PreloadHostList[%v]", idx),
				reason: "value does not have prefix \"http\"",
			}
		}

	}

	return nil
}

// PreloadReqValidationError is the validation error returned by
// PreloadReq.Validate if the designated constraints aren't met.
type PreloadReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreloadReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreloadReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreloadReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreloadReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreloadReqValidationError) ErrorName() string { return "PreloadReqValidationError" }

// Error satisfies the builtin error interface
func (e PreloadReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreloadReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreloadReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreloadReqValidationError{}

// Validate checks the field values on PreloadResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PreloadResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Msg

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PreloadRespValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// PreloadRespValidationError is the validation error returned by
// PreloadResp.Validate if the designated constraints aren't met.
type PreloadRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreloadRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreloadRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreloadRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreloadRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreloadRespValidationError) ErrorName() string { return "PreloadRespValidationError" }

// Error satisfies the builtin error interface
func (e PreloadRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreloadResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreloadRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreloadRespValidationError{}

// Validate checks the field values on PreloadInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PreloadInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Gzurl

	// no validation rules for Md5

	// no validation rules for Weburl

	return nil
}

// PreloadInfoValidationError is the validation error returned by
// PreloadInfo.Validate if the designated constraints aren't met.
type PreloadInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreloadInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreloadInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreloadInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreloadInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreloadInfoValidationError) ErrorName() string { return "PreloadInfoValidationError" }

// Error satisfies the builtin error interface
func (e PreloadInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreloadInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreloadInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreloadInfoValidationError{}
