// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"github.com/lingwei0604/kitty/app/entity"
	"github.com/lingwei0604/kitty/app/module"
	"github.com/lingwei0604/kitty/app/repository"
	"github.com/lingwei0604/kitty/pkg/config"
	"github.com/lingwei0604/kitty/pkg/contract"
	"github.com/lingwei0604/kitty/pkg/event"
	"github.com/lingwei0604/kitty/pkg/invitecode"
	"github.com/lingwei0604/kitty/pkg/khttp"
	"github.com/lingwei0604/kitty/pkg/kkafka/client"
	"github.com/lingwei0604/kitty/pkg/ots3"
	"github.com/lingwei0604/kitty/share/handlers"
	"github.com/lingwei0604/kitty/share/internal"
	"github.com/lingwei0604/kitty/share/listener"
	"github.com/go-kit/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func injectModule(reader contract.ConfigReader, logger log.Logger, dynConf config.DynamicConfigReader) (*Module, func(), error) {
	securityConfig := module.ProvideSecurityConfig(reader)
	appName := config.ProvideAppName(reader)
	env := config.ProvideEnv(reader)
	histogram := module.ProvideHistogramMetrics(appName, env)
	jaegerLogger := module.ProvideJaegerLogAdapter(logger)
	tracer, cleanup, err := module.ProvideOpentracing(jaegerLogger, reader)
	if err != nil {
		return nil, nil, err
	}
	moduleOverallMiddleware := provideEndpointsMiddleware(logger, securityConfig, histogram, tracer, env, appName)
	dialector, err := module.ProvideDialector(reader)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gormConfig := module.ProvideGormConfig(logger, reader)
	db, cleanup2, err := module.ProvideGormDB(dialector, gormConfig, tracer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	relationRepo := repository.NewRelationRepo(db)
	tokenizer := provideTokenizer(reader)
	client := module.ProvideHttpClient(tracer)
	xTaskRequester, err := internal.NewXTaskRequester(reader, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	invitationManagerFactory := internal.InvitationManagerFactory{
		Rr:     relationRepo,
		T:      tokenizer,
		C:      xTaskRequester,
		Logger: logger,
	}
	invitationManagerFacade := &internal.InvitationManagerFacade{
		Name:    appName,
		Factory: invitationManagerFactory,
		DynConf: dynConf,
	}
	manager := module.ProvideUploadManager(tracer, reader, client)
	fileRepo := repository.NewFileRepo(manager, client)
	universalClient, cleanup3 := ProvideRedis(logger, reader)
	uniqueID := repository.NewUniqueID(universalClient, reader)
	userRepo := repository.NewUserRepo(db, fileRepo, uniqueID)
	kafkaFactory, cleanup4 := module.ProvideKafkaFactory(reader, logger)
	v := providePublisherOptions(tracer, logger)
	moduleProducerMiddleware := provideProducerMiddleware(tracer, logger)
	dataStore := provideInvitationCodeBus(kafkaFactory, reader, v, moduleProducerMiddleware)
	dispatcher := provideDispatcher(dataStore)
	shareService := handlers.NewShareService(invitationManagerFacade, userRepo, dispatcher, tokenizer)
	shareServer := handlers.ProvideShareServer(shareService)
	endpoints := provideEndpoints(moduleOverallMiddleware, shareServer)
	grpcShareServer := provideGrpc(endpoints, tracer, logger, appName)
	handler := provideHttp(endpoints, tracer, logger, appName)
	server := provideKafkaServer(endpoints, kafkaFactory, reader, tracer, env, logger)
	moduleModule := provideModule(grpcShareServer, handler, server, appName)
	return moduleModule, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var ShareServiceSet = wire.NewSet(module.DbSet, module.OpenTracingSet, module.NameAndEnvSet, module.ProvideSecurityConfig, module.ProvideKafkaFactory, module.ProvideHistogramMetrics, module.ProvideHttpClient, module.ProvideUploadManager, repository.NewUserRepo, repository.NewRelationRepo, repository.NewFileRepo, repository.NewUniqueID, ProvideRedis,
	provideTokenizer,
	providePublisherOptions,
	provideInvitationCodeBus,
	provideDispatcher, internal.NewXTaskRequester, handlers.NewShareService, handlers.ProvideShareServer, wire.Struct(new(internal.InvitationManagerFactory), "*"), wire.Struct(new(internal.InvitationManagerFacade), "*"), wire.Bind(new(handlers.UserRepository), new(*repository.UserRepo)), wire.Bind(new(internal.RelationRepository), new(*repository.RelationRepo)), wire.Bind(new(handlers.InvitationManager), new(*internal.InvitationManagerFacade)), wire.Bind(new(contract.Uploader), new(*ots3.Manager)), wire.Bind(new(contract.HttpDoer), new(*khttp.Client)), wire.Bind(new(internal.EncodeDecoder), new(*invitecode.Tokenizer)), wire.Bind(new(contract.Dispatcher), new(*event.Dispatcher)), wire.Bind(new(listener.InvitationCodeBus), new(*client.DataStore)), wire.Bind(new(entity.IDAssigner), new(*repository.UniqueID)),
)
