// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"git.yingzhongshare.com/mkt/kitty/app/module"
	"git.yingzhongshare.com/mkt/kitty/pkg/config"
	"git.yingzhongshare.com/mkt/kitty/pkg/contract"
	"git.yingzhongshare.com/mkt/kitty/rule/service"
	"github.com/go-kit/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func injectModule(reader contract.ConfigReader, logger log.Logger) (*Module, func(), error) {
	client, cleanup, err := provideEtcdClient(reader)
	if err != nil {
		return nil, nil, err
	}
	repository, err := provideRepository(client, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jaegerLogger := module.ProvideJaegerLogAdapter(logger)
	tracer, cleanup2, err := module.ProvideOpentracing(jaegerLogger, reader)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	env := config.ProvideEnv(reader)
	dmpServer, err := provideDmpServer(reader, tracer, logger, env)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	universalClient, cleanup3 := module.ProvideRedis(logger, reader, tracer)
	clihttpClient := ProvideHTTPClient(tracer)
	serviceService := service.ProvideService(logger, repository, dmpServer, universalClient, clihttpClient)
	appName := config.ProvideAppName(reader)
	histogram := provideHistogramMetrics(appName, env)
	endpoints := newEndpoints(serviceService, histogram, logger, appName, env)
	moduleModule := provideModule(repository, endpoints, tracer, logger)
	return moduleModule, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var serviceSet = wire.NewSet(
	provideEtcdClient,
	provideRepository, service.ProvideService,
)
